### ISSUE TITLE
shadertype doesn't work in VS2015

### ISSUE THREAD

**Issue by chinhodado** [samizzo/nshader#1]
I have two shader files with extensions `.fs` and `.vs`. I have put `// shadertype=glsl` as the first line of the two files but there's no syntax highlighting. Changing the extensions to `.frag` and `.vert` works.

Running VS2015 Community.

**Comment by samizzo** [comment]
Thanks, that makes sense. The supported file extensions are hard-coded unfortunately, due to the way Visual Studio extensions work. I've been meaning to see if I can change that.

**Comment by chinhodado** [comment]
I don't have any experience with making VS extension but I did some quick research and this commit seems relevant:

https://github.com/NoahRic/MarkdownMode/commit/3d8685d1042af09445d1aa35d24d0f2d060bcf12

The file extension list is [here](https://github.com/NoahRic/MarkdownMode/commit/3d8685d1042af09445d1aa35d24d0f2d060bcf12#diff-a079a77f1e8c3a779a0df293f721b1a8R32) and it is used [here](https://github.com/NoahRic/MarkdownMode/commit/3d8685d1042af09445d1aa35d24d0f2d060bcf12#diff-a079a77f1e8c3a779a0df293f721b1a8R83), so maybe it is possible to use a wildcard like *.* there directly?

**Comment by samizzo** [comment]
I've made a change to allow this to work. The latest version now lets you add extensions via Tools->Options->Text Editor->File Extension. You can assign them to "NShader Editor". Let me know if it works for you. I've updated the README and made a new post at http://www.horsedrawngames.com that discusses the details.

**Comment by chinhodado** [comment]
That works great for me, thanks a lot!

On a side note, it wouldn't let me upgrade the extension so I had to uninstall and reinstall. Not sure why.

Also, you can consider release the extension file directly on Github (use the release tab). It's easier to tie a release binary to a commit/tag/version that way.

**Comment by samizzo** [comment]
Hm yeah I can never seem to upgrade it either. I'll see if I can figure it out. Thanks for the tip about releases! I'll do that.

**Comment by dasmysh** [comment]
Thanks for the new version. Works great for me.
