### ISSUE TITLE
Any plans to add VS2017 compatibility?

### ISSUE THREAD

**Issue by ghost** [samizzo/nshader#10]
Hi, Sam -

I've grown very accustomed to having this add-in as part of my VS environment. I'd be heartbroken if I had to leave it behind as I migrate to VS2017...

Signed:
A concerned fan.

**Comment by samizzo** [comment]
Hi concerned fan!

I didn't have plans to add VS2017 support because I'm not using it yet, but since you asked nicely I'll do it!

**Comment by ghost** [comment]
Hi, Sam –

 

Outstanding. You da man.

 

:)

 

Thanks again.

**Comment by samizzo** [comment]
Ok I added VS2017 support and pushed a new release (2.3). Let me know if you have any troubles with it!

**Comment by ghost** [comment]
Awesome, Sam. I appreciate it. I’ll let you know is I see an behavior different from the previous VS version.

 

Thanks again.
