### ISSUE TITLE
'Fonts and Colors' entries don't appear in VS2017

### ISSUE THREAD

**Issue by ghost** [samizzo/nshader#11]
Hi, Sam -

Bad news, I'm afraid. While the new version does appear to have installed in VS2017, none of the 'fonts and colors' entries (e.g., 'NShader - Comment') appear in the options dialog. The add-in DOES seem to have installed - it appears in the 'Extensions and Updates' dialog as an installed Add-in. 

And here's a possible clue - when I ran the installer, two VS versions appeared in the list as available to have the add-in installed - VS2015 Pro and VS2017 Pro. I unchecked VS2015 (as the previous rev was already installed there), and checked the VS2017 checkbox, and started the install. Installer reported success on finish. I then opened VS2015, and after it had finished initializing, opened VS2017. Here's the thing - VS2015 displayed the sequence of dialogs at start-up you typically see when an add-in is installed - you know, 'scanning mef components', 'building mef components graph', or something like that. VS2017 showed no such dialog sequence at start-up - it made no indication that an add-in had been installed.

Again - I hadn't select VS2015, but had selected VS2017.

I hope this is useful info.

**Comment by samizzo** [comment]
Ah bugger! Ok thanks for that. Sorry I dropped the ball, I only tested that it would install and didn't actually check that it was working! I'll look into it.

**Comment by samizzo** [comment]
Hmm, ok so the 'fonts and colours' entries weren't there for me either. However, then I loaded a glsl file and the extension then seemed to initialise itself and the entries appeared! Can you try that? I think this might be a 2017 quirk. They seem to have made a lot of changes to improve load times, and I suspect one might be to not initialise the extensions until they are needed.

**Comment by samizzo** [comment]
At first I thought it might be related to this new "[lightweight solution load](https://docs.microsoft.com/en-us/visualstudio/extensibility/lightweight-solution-load-extension-impact)" feature but I don't have that turned on so I don't think it's that.

**Comment by ghost** [comment]
Hi, Sam –

 

You’re right! I hadn’t thought of trying that – my bad.

 

So it’s all good.

 

Thanks again for your efforts.

 

 

HB

**Comment by samizzo** [comment]
Awesome thanks!
