### ISSUE TITLE
Serious bug...

### ISSUE THREAD

**Issue by AzP** [samizzo/nshader#3]
... is not what this is. I just wanted to thank you for maintaining this! Strangely enough it was a bit hard to find though, I think you should recommend it in some different forums and perhaps get the word out.

I only ever found the original NShader which doesn't work for 2013/2015.

Thank you again!

**Comment by samizzo** [comment]
Haha thanks! :) What forums do you suggest? I posted on the Unity forums which is where I originally found NShader, and a Facebook group for local (to me) developers. I also tweeted about it and posted on my blog but those are low traffic :)

**Comment by AzP** [comment]
I was thinking the StackOverflow questions where people ask for GLSL support in Visual Studio, etc. If you google for "visual studio glsl" you'll get a couple of forums and some SO questions. Perhaps create a question on gamedev.stackexchange.com and answer it yourself? I don't know if that is against some rule, but I think it shouldn't be since you're actually answering a question.

The gamedev forum and the OpenGL forum is definitely good places.

**Comment by samizzo** [comment]
Thanks, good idea!
